# TCL File Generated by Component Editor 20.1
# Fri Jan 01 00:47:52 JST 2021
# DO NOT MODIFY


# 
# KyogenRV "kyogenrv32" v20.1
#  2021.01.01.00:47:52
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module KyogenRV
# 
set_module_property DESCRIPTION ""
set_module_property NAME KyogenRV
set_module_property VERSION 20.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME kyogenrv32
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL kyogenrv_fpga_avalonMM
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file kyogenrv_fpga_avalonMM.sv SYSTEM_VERILOG PATH kyogenrv_fpga_avalonMM.sv TOP_LEVEL_FILE
add_fileset_file KyogenRVCpu.v VERILOG PATH ../chisel_generated/KyogenRVCpu.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point avalon_data_master
# 
add_interface avalon_data_master avalon start
set_interface_property avalon_data_master addressUnits SYMBOLS
set_interface_property avalon_data_master associatedClock clock
set_interface_property avalon_data_master associatedReset reset
set_interface_property avalon_data_master bitsPerSymbol 8
set_interface_property avalon_data_master burstOnBurstBoundariesOnly false
set_interface_property avalon_data_master burstcountUnits WORDS
set_interface_property avalon_data_master doStreamReads false
set_interface_property avalon_data_master doStreamWrites false
set_interface_property avalon_data_master holdTime 0
set_interface_property avalon_data_master linewrapBursts false
set_interface_property avalon_data_master maximumPendingReadTransactions 0
set_interface_property avalon_data_master maximumPendingWriteTransactions 0
set_interface_property avalon_data_master readLatency 0
set_interface_property avalon_data_master readWaitTime 1
set_interface_property avalon_data_master setupTime 0
set_interface_property avalon_data_master timingUnits Cycles
set_interface_property avalon_data_master writeWaitTime 0
set_interface_property avalon_data_master ENABLED true
set_interface_property avalon_data_master EXPORT_OF ""
set_interface_property avalon_data_master PORT_NAME_MAP ""
set_interface_property avalon_data_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_data_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_data_master dmem_addr address Output 32
add_interface_port avalon_data_master dmem_waitrequest waitrequest Input 1
add_interface_port avalon_data_master r_dmem_data readdata Input 32
add_interface_port avalon_data_master r_dmem_data_ack readdatavalid Input 1
add_interface_port avalon_data_master r_dmem_data_req read Output 1
add_interface_port avalon_data_master w_dmem_data writedata Output 32
add_interface_port avalon_data_master w_dmem_data_byteenable byteenable Output 4
add_interface_port avalon_data_master w_dmem_data_req write Output 1


# 
# connection point avalon_inst_master
# 
add_interface avalon_inst_master avalon start
set_interface_property avalon_inst_master addressUnits SYMBOLS
set_interface_property avalon_inst_master associatedClock clock
set_interface_property avalon_inst_master associatedReset reset
set_interface_property avalon_inst_master bitsPerSymbol 8
set_interface_property avalon_inst_master burstOnBurstBoundariesOnly false
set_interface_property avalon_inst_master burstcountUnits WORDS
set_interface_property avalon_inst_master doStreamReads false
set_interface_property avalon_inst_master doStreamWrites false
set_interface_property avalon_inst_master holdTime 0
set_interface_property avalon_inst_master linewrapBursts false
set_interface_property avalon_inst_master maximumPendingReadTransactions 0
set_interface_property avalon_inst_master maximumPendingWriteTransactions 0
set_interface_property avalon_inst_master readLatency 0
set_interface_property avalon_inst_master readWaitTime 1
set_interface_property avalon_inst_master setupTime 0
set_interface_property avalon_inst_master timingUnits Cycles
set_interface_property avalon_inst_master writeWaitTime 0
set_interface_property avalon_inst_master ENABLED true
set_interface_property avalon_inst_master EXPORT_OF ""
set_interface_property avalon_inst_master PORT_NAME_MAP ""
set_interface_property avalon_inst_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_inst_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_inst_master r_imem_data_req read Output 1
add_interface_port avalon_inst_master imem_addr address Output 32
add_interface_port avalon_inst_master r_imem_data_ack readdatavalid Input 1
add_interface_port avalon_inst_master r_imem_data readdata Input 32
add_interface_port avalon_inst_master imem_waitrequest waitrequest Input 1
add_interface_port avalon_inst_master w_imem_data_byteenable byteenable Output 4


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock clk Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end ex_inst readdata Output 32


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1

